name: Slack Shift Notifications

on:
  schedule:
    - cron: "0 9 * * *"  # 毎日 9:00
  workflow_dispatch:  # 手動実行も可能

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Call Slack Shift Notification API
        run: |
          curl -X POST https://your-domain.com/api/slack \
          -H "Content-Type: application/json" \
          -d '{"action": "send_shift_notifications"}'
